export const WAITLIST_SUBMIT = 'WAITLIST_SUBMIT';
export const WAITLIST_SUBMIT_SUCCESS = 'WAITLIST_SUBMIT_SUCCESS';
export const WAITLIST_SUBMIT_FAIL = 'WAITLIST_SUBMIT_FAIL';
export const WAITLIST_USER_FETCH_SUCCESS = 'WAITLIST_SUBMIT_FAIL';
